//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONPE.WEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class 
        ONPEWEBEntities : DbContext
    {
        public ONPEWEBEntities()
            : base("name=ONPEWEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidato> Candidato { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<PartidoPolitico> PartidoPolitico { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
